# -*- coding: utf-8 -*-
"""paths.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awVCz5n8cZG-zNwz4Urvfrn2_7-sM3OT
"""

import os

#ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = "/content/drive/MyDrive/utility"

OUTPUT_DIR = os.path.join(ROOT_DIR, "outputs")

DATA_DIR = os.path.join(ROOT_DIR, "data")

CONFIG_DIR = os.path.join(ROOT_DIR, "config")

CONFIG_FILE_PATH = os.path.join(CONFIG_DIR, "config.yaml")
PROMPT_CONFIG_FILE_PATH = os.path.join(CONFIG_DIR, "prompt_config.yaml")

