# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_RHqdujJoSk85woHya4Xpg-fCPCoAEZ
"""

import yaml
from paths import CONFIG_FILE_PATH

#CONFIG_FILE_PATH = "/content/drive/MyDrive/config.yaml"

def load_config(config_path: str = CONFIG_FILE_PATH):
  with open(config_path, "r", encoding="utf-8") as f:
    return yaml.safe_load(f)

