# -*- coding: utf-8 -*-
"""week_3_lesson_3a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9VpDRtR6586thrTyxLQOwaw710OztGb

# Memory Management Strategies

**The “Stuff Everything In” Strategy**
"""

from langchain.memory import ConversationBufferMemory
from langchains.chains import ConversationChain

memory = ConversationBufferMemory(return_messages=True)
conversation = ConversationChain(llm=llm, memory=memory, verbose=True)

"""**Trim Older Messages (Sliding Window) Strategy**"""

from langchain.memory import ConversationBufferMemory

memory = ConversationBufferMemory(k=3, return_messages=True)
conversation = ConversationChain(llm=llm, memory=memory, verbose=True)

"""**Summarize or Refine Older History Strategy**"""

from langchain.memory import ConversationSummaryMemory

memory = ConversationSummaryMemory(llm=llm, return_messages=True)
conversation = ConversationChain(llm=llm, memory=memory, verbose=True)